services:
 dev-db:
  image: postgres:13
  env_file:
    - .env
  ports:
   - 5434:5432
  environment: 
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRE_DB: ${POSTGRES_DB}
  networks:
    ia-e-commerce:
networks:
  ia-e-commerce:
