services:
 dev-db:
  image: postgres:13
  ports:
   - 5434:5432
  environment: 
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 123
    POSTGRE_DB: nest1
  networks:
    ia-e-commerce:
networks:
  ia-e-commerce:
